# frozen_string_literal: true

module Pangea
  module Testing
    # Auto-generates RSpec architecture specs from composition metadata.
    #
    # Usage:
    #   generator = ArchitectureSpecGenerator.new(
    #     module_name: 'Pangea::Architectures::K3sDevCluster',
    #     required_config: { cluster_name: 'test', account_id: '123456789012', ... },
    #     expected_resources: {
    #       'aws_vpc' => ['test-vpc'],
    #       'aws_subnet' => ['test-public'],
    #       'aws_iam_role' => ['test-node'],
    #     },
    #     expected_refs: [:vpc, :subnet, :iam],
    #     required_tags: %w[ManagedBy Purpose Environment],
    #     security_invariants: [
    #       { type: :no_wildcard_actions },
    #       { type: :no_public_ssh },
    #       { type: :encrypted_volumes },
    #     ],
    #   )
    #   puts generator.generate
    #
    class ArchitectureSpecGenerator
      attr_reader :config

      def initialize(**config)
        @config = config
      end

      def generate
        [header, synthesis_spec, security_spec].compact.join("\n\n")
      end

      def generate_synthesis
        [header, synthesis_spec].join("\n")
      end

      def generate_security
        [header, security_spec].join("\n")
      end

      private

      def module_name = config[:module_name]
      def required_config = config[:required_config] || {}
      def expected_resources = config[:expected_resources] || {}
      def expected_refs = config[:expected_refs] || []
      def required_tags = config[:required_tags] || %w[ManagedBy Purpose Environment]
      def security_invariants = config[:security_invariants] || []

      def header
        <<~RUBY
          # frozen_string_literal: true
          # Auto-generated by Pangea::Testing::ArchitectureSpecGenerator

          require 'spec_helper'
        RUBY
      end

      def synthesis_spec
        tests = []
        tests << terraform_structure_test
        expected_resources.each { |type, names| names.each { |n| tests << resource_exists_test(type, n) } }
        tests << returns_refs_test unless expected_refs.empty?
        tests << determinism_test
        tests << tag_test unless required_tags.empty?
        tests << validation_tests

        <<~RUBY
          RSpec.describe #{module_name} do
            include Pangea::Testing::SynthesisTestHelpers

            describe '.build' do
              let(:synth) { create_synthesizer }
              let(:default_config) { #{format_hash(required_config)} }
              let(:result) do
                described_class.build(synth, default_config)
                normalize_synthesis(synth.synthesis)
              end

          #{tests.map { |t| indent(t, 4) }.join("\n\n")}
            end
          end
        RUBY
      end

      def security_spec
        return nil if security_invariants.empty?
        sec_tests = security_invariants.map { |inv| security_test(inv) }
        <<~RUBY
          RSpec.describe '#{module_name.split('::').last} security invariants' do
            include Pangea::Testing::SynthesisTestHelpers

            let(:synth) { create_synthesizer }
            let(:config) { #{format_hash(required_config)} }
            let(:result) do
              #{module_name}.build(synth, config)
              normalize_synthesis(synth.synthesis)
            end

          #{sec_tests.map { |t| indent(t, 2) }.join("\n\n")}
          end
        RUBY
      end

      def terraform_structure_test
        <<~RUBY
          it 'produces valid Terraform JSON' do
            validate_terraform_structure(result, :resource)
          end
        RUBY
      end

      def resource_exists_test(type, name)
        <<~RUBY
          it 'creates #{type} #{name}' do
            validate_resource_structure(result, '#{type}', '#{name}')
          end
        RUBY
      end

      def returns_refs_test
        ref_assertions = expected_refs.map { |r| "  expect(refs).to have_key(:#{r})" }.join("\n")
        <<~RUBY
          it 'returns all expected resource references' do
            refs = described_class.build(synth, default_config)
          #{ref_assertions}
          end
        RUBY
      end

      def determinism_test
        <<~RUBY
          it 'produces deterministic output' do
            s1 = create_synthesizer
            described_class.build(s1, default_config)

            s2 = create_synthesizer
            described_class.build(s2, default_config)

            expect(s1.synthesis.to_json).to eq(s2.synthesis.to_json)
          end
        RUBY
      end

      def tag_test
        tag_assertions = required_tags.map { |t| "  expect(tagged_resource['tags']).to have_key('#{t}')" }.join("\n")
        <<~RUBY
          it 'applies required tags' do
            # Check first resource type for tags
            all_resources = result['resource'] || {}
            tagged_resource = all_resources.values.first&.values&.first
            next unless tagged_resource&.key?('tags')
          #{tag_assertions}
          end
        RUBY
      end

      def validation_tests
        <<~RUBY
          context 'validation' do
            it 'raises on empty config' do
              expect { described_class.build(synth, {}) }.to raise_error(ArgumentError)
            end
          end
        RUBY
      end

      def security_test(invariant)
        case invariant[:type]
        when :no_wildcard_actions
          <<~RUBY
            it 'never uses wildcard actions' do
              policies = result.dig('resource', 'aws_iam_policy') || {}
              policies.each do |name, config|
                policy = JSON.parse(config['policy'])
                policy['Statement'].each do |stmt|
                  Array(stmt['Action']).each do |action|
                    expect(action).not_to eq('*'), "Policy \#{name} has wildcard action"
                  end
                end
              end
            end
          RUBY
        when :no_public_ssh
          <<~RUBY
            it 'does not allow SSH from 0.0.0.0/0' do
              sgs = result.dig('resource', 'aws_security_group') || {}
              sgs.each do |name, config|
                rules = Array(config['ingress'] || config['ingress_rules'])
                ssh_rules = rules.select { |r| r['from_port'] == 22 }
                ssh_rules.each do |rule|
                  expect(Array(rule['cidr_blocks'])).not_to include('0.0.0.0/0')
                end
              end
            end
          RUBY
        when :encrypted_volumes
          <<~RUBY
            it 'uses encrypted volumes on all instances' do
              instances = result.dig('resource', 'aws_instance') || {}
              instances.each do |name, config|
                expect(config.dig('root_block_device', 'encrypted')).to eq(true),
                  "Instance \#{name} must have encrypted root volume"
              end
            end
          RUBY
        else
          "# Unknown invariant: #{invariant[:type]}"
        end
      end

      def format_hash(hash, depth = 0)
        return '{}' if hash.empty?
        pad = '  ' * (depth + 1)
        inner = hash.map do |k, v|
          case v
          when Hash then "#{pad}#{k}: #{format_hash(v, depth + 1)}"
          when Symbol then "#{pad}#{k}: :#{v}"
          when String then "#{pad}#{k}: '#{v}'"
          when Array then "#{pad}#{k}: #{v.inspect}"
          else "#{pad}#{k}: #{v.inspect}"
          end
        end.join(",\n")
        "{\n#{inner},\n#{'  ' * depth}}"
      end

      def indent(text, level)
        prefix = '  ' * level
        text.lines.map { |line| line.strip.empty? ? line : "#{prefix}#{line}" }.join
      end
    end
  end
end
