# frozen_string_literal: true

module Pangea
  module Testing
    # Auto-generates RSpec synthesis specs from resource metadata.
    #
    # Usage:
    #   generator = SpecGenerator.new(
    #     provider_module: 'Pangea::Resources::AWS',
    #     resource_type: 'aws_iam_instance_profile',
    #     attributes_class: 'Pangea::Resources::AWS::Types::IamInstanceProfileAttributes',
    #     required_attributes: { name: 'test-profile', role: 'test-role' },
    #     optional_attributes: { path: '/custom/', tags: { Env: 'test' } },
    #     expected_outputs: [:id, :arn, :name, :unique_id],
    #     mutually_exclusive: [[:name, :name_prefix]],
    #     terraform_ref_fields: [:role, :name],
    #     supports_tags: true,
    #   )
    #   puts generator.generate
    #
    class SpecGenerator
      HEADER = <<~RUBY.freeze
        # frozen_string_literal: true
        # Auto-generated by Pangea::Testing::SpecGenerator
        # Regenerate with: pangea-core spec-gen or forge pangea-spec-gen

        require 'spec_helper'
      RUBY

      attr_reader :config

      def initialize(**config)
        @config = config
        validate_config!
      end

      def generate
        [
          HEADER,
          describe_block,
        ].join("\n")
      end

      private

      def provider_module = config[:provider_module]
      def resource_type = config[:resource_type]
      def required_attrs = config[:required_attributes] || {}
      def optional_attrs = config[:optional_attributes] || {}
      def expected_outputs = config[:expected_outputs] || [:id]
      def mutually_exclusive = config[:mutually_exclusive] || []
      def tf_ref_fields = config[:terraform_ref_fields] || []
      def supports_tags = config.fetch(:supports_tags, true)

      def describe_block
        tests = []
        tests << synthesis_test
        tests << reference_test
        tests << tags_test if supports_tags
        tf_ref_fields.each { |field| tests << terraform_ref_test(field) }
        mutually_exclusive.each { |pair| tests << mutually_exclusive_test(pair) }

        <<~RUBY
          RSpec.describe '#{resource_type}' do
            let(:synthesizer) { TerraformSynthesizer.new }

          #{tests.map { |t| indent(t, 2) }.join("\n\n")}
          end
        RUBY
      end

      def synthesis_test
        <<~RUBY
          it 'synthesizes with valid attributes' do
            synthesizer.instance_eval do
              extend #{provider_module}
              #{resource_type}(:test, #{format_hash(required_attrs)})
            end
            result = synthesizer.synthesis
            config = result[:resource][:#{resource_type}][:test]
            expect(config).to be_a(Hash)
          end
        RUBY
      end

      def reference_test
        output_assertions = expected_outputs.map do |output|
          "  expect(ref.outputs[:#{output}]).to eq('${#{resource_type}.test.#{output}}')"
        end.join("\n")

        <<~RUBY
          it 'returns ResourceReference with correct outputs' do
            ref = synthesizer.instance_eval do
              extend #{provider_module}
              #{resource_type}(:test, #{format_hash(required_attrs)})
            end
            expect(ref).to be_a(Pangea::Resources::ResourceReference)
            expect(ref.type).to eq('#{resource_type}')
            expect(ref.name).to eq(:test)
          #{output_assertions}
          end
        RUBY
      end

      def tags_test
        tagged = required_attrs.merge(tags: { Environment: 'test', Team: 'platform' })
        <<~RUBY
          it 'synthesizes with tags' do
            synthesizer.instance_eval do
              extend #{provider_module}
              #{resource_type}(:test, #{format_hash(tagged)})
            end
            result = synthesizer.synthesis
            config = result[:resource][:#{resource_type}][:test]
            expect(config[:tags]).to be_a(Hash) if config[:tags]
          end
        RUBY
      end

      def terraform_ref_test(field)
        ref_attrs = required_attrs.merge(field => '${other.resource.id}')
        <<~RUBY
          it 'accepts Terraform references in #{field}' do
            expect {
              synthesizer.instance_eval do
                extend #{provider_module}
                #{resource_type}(:test, #{format_hash(ref_attrs)})
              end
            }.not_to raise_error
          end
        RUBY
      end

      def mutually_exclusive_test(fields)
        both_set = required_attrs.merge(fields.map { |f| [f, "value-#{f}"] }.to_h)
        <<~RUBY
          it 'rejects both #{fields.join(" and ")} set simultaneously' do
            expect {
              synthesizer.instance_eval do
                extend #{provider_module}
                #{resource_type}(:test, #{format_hash(both_set)})
              end
            }.to raise_error(Dry::Struct::Error)
          end
        RUBY
      end

      def format_hash(hash, depth = 0)
        return '{}' if hash.empty?
        pad = '  ' * (depth + 1)
        inner = hash.map do |k, v|
          case v
          when Hash then "#{pad}#{k}: #{format_hash(v, depth + 1)}"
          when Symbol then "#{pad}#{k}: :#{v}"
          when String then "#{pad}#{k}: '#{v.gsub("'", "\\\\'")}'"
          when Array then "#{pad}#{k}: #{v.inspect}"
          when TrueClass, FalseClass, Integer, Float then "#{pad}#{k}: #{v}"
          else "#{pad}#{k}: #{v.inspect}"
          end
        end.join(",\n")
        "{\n#{inner},\n#{'  ' * depth}}"
      end

      def indent(text, level)
        prefix = '  ' * level
        text.lines.map { |line| line.strip.empty? ? line : "#{prefix}#{line}" }.join
      end

      def validate_config!
        raise ArgumentError, ':provider_module is required' unless config[:provider_module]
        raise ArgumentError, ':resource_type is required' unless config[:resource_type]
        raise ArgumentError, ':required_attributes is required' unless config[:required_attributes]
      end
    end
  end
end
